# Generated by Django 5.1.2 on 2024-10-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='message',
        ),
    ]
