# Generated by Django 5.1.2 on 2024-10-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHim', '0002_remove_record_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.AddField(
            model_name='record',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
