# Generated by Django 5.1.2 on 2024-10-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHim', '0005_userformdata_remove_record_user_delete_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFormData',
            new_name='UserForm',
        ),
    ]
