# Generated by Django 5.1.2 on 2024-10-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHim', '0007_rename_userform_userformdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFormData',
            new_name='UserForm',
        ),
    ]
