# Generated by Django 5.1.2 on 2024-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHim', '0008_rename_userformdata_userform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
